server:
  port: 8083

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/allrounder
      client:
        registration:
          keycloak:
            client-id: allrounder-client
            client-secret: your-client-secret
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/allrounder

# Keycloak 설정
keycloak:
  server-url: http://localhost:8080
  realm: allrounder
  client-id: allrounder-client
  client-secret: your-client-secret
  admin:
    username: admin
    password: admin

# JWT 설정 (로컬 JWT용)
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production
  expiration: 86400000 # 24시간
  refresh-expiration: 604800000 # 7일

# 보안 정책 설정
security:
  policy:
    rbac:
      enabled: true
    abac:
      enabled: false # 향후 확장용
    pbac:
      enabled: false # 향후 확장용

logging:
  level:
    rounderall.security: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
