server:
  port: 8083

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production
  expiration: 86400000 # 24시간

logging:
  level:
    rounderall.security: DEBUG
    org.springframework.security: DEBUG
